version: '3.1'

services:

  postgres:
    image: postgres:18
    container_name: asyncpg-engine-postgres
    environment:
      POSTGRES_PASSWORD: guest
      POSTGRES_USER: guest
      POSTGRES_DB: guest
    ports:
      - 5432:5432
